---
title: "final_figures"
format: html
---

```{r}
library(tidyverse)
library(here)
library(vegan)

subtidal <- read_csv(here("data", "ucsb_fish_clean_obs_1999-2024.csv"))
taxon <- read_csv(here("data", "PISCO_kelpforest_taxon_table.1.3.csv")) %>% 
  filter(campus == "UCSB")

fish_taxon <- left_join(subtidal, taxon, by = "classcode") %>% 
  select(year, site, side, zone, level, transect, classcode, fish_tl, depth, pctcnpy, count, Family, Genus, Species, common_name) %>% 
  janitor::clean_names()

fish_role <- read_csv(here("data", "ucsb_fish_clean_tx_bm_1999-2024.csv")) %>% 
  filter(year > 2005) %>% 
  select(classcode, BroadTrophic, Targeted) %>%
  distinct() %>%
  group_by(classcode) %>% 
  summarise(BroadTrophic = paste(BroadTrophic, collapse = ", "),
            Targeted = paste(Targeted, collapse = ", "),
    .groups = 'drop') %>% 
  janitor::clean_names()


fish <- left_join(fish_taxon, fish_role, by = "classcode") %>% 
  janitor::clean_names()

```

```{r}
fish_clean <- fish %>% 
  filter(!is.na(fish_tl)) %>%
  group_by(site) %>% 
  mutate(total_years = length(unique(year))) %>% # Calculate number of years each site was surveyed
  ungroup() %>%
  mutate(island = case_when( # Assign sites to respective islands
    str_detect(pattern = "SRI", string = site) ~ "Santa Rosa", 
    str_detect(pattern = "SCI", string = site) ~ "Santa Cruz",
    str_detect(pattern = "SMI", string = site) ~ "San Miguel",
    str_detect(pattern = "ANA", string = site) ~ "Anacapa",
    TRUE ~ "remove"), 
    level = factor(level, levels = c("CAN", "MID", "BOT"))) %>% # Refactor survey levels
  filter(island != "remove", 
         total_years >= 15,
         year > 2005) %>% # Select only sites with >=15 years of surveys
  select(-total_years)
```

```{r}
# Calculate canopy averages at transect level
kelp <- fish_clean %>% 
  group_by(site, side, transect, year) %>% 
  summarise(av_pctcnpy = round(mean(pctcnpy, na.rm = TRUE), digits = 0)) %>% 
  ungroup() %>%
  mutate(cnpy_pct = case_when( # Bin percent canopy cover
    av_pctcnpy <= 10 ~ "0-10",
    av_pctcnpy <= 20 ~ "11-20",
    av_pctcnpy <= 30 ~ "21-30",
    av_pctcnpy <= 40 ~ "31-40",
    av_pctcnpy <= 50 ~ "41-50",
    av_pctcnpy <= 60 ~ "51-60",
    av_pctcnpy <= 70 ~ "61-70",
    av_pctcnpy <= 80 ~ "71-80",
    av_pctcnpy <= 90 ~ "81-90",
    av_pctcnpy > 90 ~ "91-100",
    TRUE ~ NA,
    )
  ) %>% 
  filter(!is.na(cnpy_pct))

fish_kelp <- left_join(fish_clean, kelp, by = join_by(site, side, transect, year)) # Attach bins to data

```
```{r}
species_sums <- fish_kelp %>% 
  group_by(family) %>% 
  mutate(total_obs = n(),
         total_counts = sum(count)) %>% 
  ungroup() %>% 
  mutate(fish_family = case_when(
    total_counts >= 30000 ~ family,
    TRUE ~ "Other"))
```


```{r}
# Color palettes
plot_palette = c("#001806", "#7F6F2B", "#9A7408", "#D4C569", "#AA9D52", "#EBF4F2", "#B6E5F0", "#96B8A9", "#1E6848", "#004B5D", "#002B2B")
fish = c("#8C6E56", "#CFCDCB", "#F7CE7B", "#E38023", "#F15739", "#823E57", "#4761B4")
```

```{r}
ggplot(species_sums, aes(cnpy_pct, count, fill = fish_family)) +
  geom_col(position = "fill") +
  scale_fill_manual(values = fish) +
  scale_y_continuous(labels = scales::percent) +
  labs(y = "",
       x = "Percent Kelp Canopy Cover",
       title = "Proportion of Fish Families Under Varying Densities of Kelp Canopy",
       fill = "Family") +
  facet_wrap(~level, ncol = 1) +
  theme_light()
```
```{r}
ggplot(species_sums, aes(pctcnpy)) +
  geom_density(aes(fill = fish_family), position = "dodge", alpha = 0.5) +
  #facet_wrap(~level, ncol = 1)
  theme_light()
```
```{r}
library(ggExtra)

fish_kelp %>% 
  mutate(depth_ft = round(depth * 3.28084, digits = 0), # convert depth from meters to feet
    depth_zone = case_when(
      depth_ft <= 10 ~ "0-10",
      depth_ft <= 20 ~ "11-20",
      depth_ft <= 30 ~ "21-30",
      depth_ft <= 40 ~ "31-40",
      depth_ft <= 50 ~ "41-50",
      depth_ft > 50 ~ ">50",
      TRUE ~ NA
  )) %>% 
  filter(!is.na(depth_zone)) %>% 
  mutate(depth_zone = forcats::fct_relevel(depth_zone,
         ">50", "41-50", "31-40", "21-30", "11-20", "0-10")) %>% 
  group_by(cnpy_pct, depth_zone, classcode) %>% 
  summarise(num_sp = sum(count),
         n = num_sp*(num_sp-1)) %>% 
  ungroup() %>% 
  group_by(cnpy_pct, depth_zone,) %>% 
  summarize(total_indiv = sum(num_sp),
         N = total_indiv*(total_indiv-1),
         biodiv = N / sum(n)) %>% 
  filter(!is.infinite(biodiv)) %>%
      #av_species = mean(length(unique(classcode)), rm.na = TRUE)) %>% 
  ggplot(aes(cnpy_pct, depth_zone, fill = biodiv)) +
  geom_tile() +
  scale_fill_gradient(high = "#002B2B", low = "#D4C569") +
  labs(x = "Kelp Density (%)",
       y = "Depth zone (ft)",
       fill = "Biodiversity\nIndex",
       title = "Biodiversity through the water column") +
  theme_light() +
  theme(panel.background = element_rect(fill = "#EBF4F2"),
        plot.background = element_rect(fill = "#EBF4F2"),
        legend.background = element_rect(fill = "#EBF4F2"), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        text = element_text(color = "#001806"))
```
```{r}
fish_kelp %>% 
  mutate(depth_ft = round(depth * 3.28084, digits = 0), # convert depth from meters to feet
    depth_zone = case_when(
      depth_ft <= 10 ~ "0-10",
      depth_ft <= 20 ~ "11-20",
      depth_ft <= 30 ~ "21-30",
      depth_ft <= 40 ~ "31-40",
      depth_ft <= 50 ~ "41-50",
      depth_ft > 50 ~ ">50",
      TRUE ~ NA
  )) %>% 
  mutate(depth_zone = forcats::fct_relevel(depth_zone,
         ">50", "41-50", "31-40", "21-30", "11-20", "0-10")) %>% 
  group_by(cnpy_pct, classcode) %>% 
  summarise(num_sp = sum(count),
         n = num_sp*(num_sp-1)) %>% 
  ungroup() %>% 
  group_by(cnpy_pct) %>% 
  summarize(total_indiv = sum(num_sp),
         N = total_indiv*(total_indiv-1),
         biodiv = N / sum(n)) %>% 
              
  
  
              
      #av_species = mean(length(unique(classcode)), rm.na = TRUE)) %>% 
  ggplot(aes(cnpy_pct, biodiv)) +
  geom_col() +
  scale_fill_gradient(high = "#002B2B", low = "#D4C569")
```

```{r}
fish_kelp %>% 
  mutate(depth_ft = depth * 3.28084, # convert depth from meters to feet
    depth_zone = case_when(
      depth_ft <= 10 ~ "0-10",
      depth_ft <= 20 ~ "11-20",
      depth_ft <= 30 ~ "21-30",
      depth_ft <= 40 ~ "31-40",
      depth_ft <= 50 ~ "41-50",
      depth_ft > 50 ~ ">50",
      TRUE ~ "NA"
  )) %>% 
  mutate(depth_zone = forcats::fct_relevel(depth_zone,
         ">50", "41-50", "31-40", "21-30", "11-20", "0-10")) %>%
  group_by(cnpy_pct, depth_zone) %>% 
  mutate(total = sum(count)) %>%
  group_by(cnpy_pct, depth_zone, classcode) %>% 
  mutate(num_sp = sum(count),
            p = num_sp/unique(total)) %>% 
  ungroup() %>% 
  group_by(cnpy_pct, depth_zone) %>% 
  mutate(H = -sum(p * log(p)),
            total_sp = length(unique(classcode)),
            evenness = H / total_sp) %>% 
              
  
  
              
      #av_species = mean(length(unique(classcode)), rm.na = TRUE)) %>% 
  ggplot(aes(cnpy_pct, depth_zone, fill = H)) +
  geom_tile() +
  scale_fill_gradient(high = "#001B2B", low = "#C4C569")
```

